# Config file for running the BackBLAST pipeline

## Execution settings
# Total threads to be used for all processes
threads: 4
# Max. memory, in Gigabytes
memory: 8


## BLAST input files
# Query files
  # query_genes contains the genes you want to do a reciprocal BLAST search with.
  # query_genome_orfs contains all predicted ORFs from the query genome (for reciprocal BLAST purposes)
query_genes: /path/to/e_coli_J625DW_query_genes.faa
query_genome_orfs: /path/to/e_coli_J625DW_query_genes.faa
# Subject files for BLAST (the name you specify will be plotted).
  # These should be ORF predictions from the genomes of the organisms of interest.
  # If you want to plot the query genome as well, then include it here.
subjects:
  E_coli_J625DW: /path/to/e_coli_J625DW_orfs.faa
  B_subtilis_168: /path/to/b_subtilis_168_orfs.faa


## Plot input files
# Newick file of phylogenetic tree for the input genomes. Should already be in the orientation that you want it to be plotted in.
  # Tree must contain EXACTLY the same organisms as in the 'subjects' above, with the EXACT same names provided for the subjects
phylogenetic_tree_newick: /path/to/phylogenetic_tree.nwk
# Optional: Tab-separated file containing the 'subject_name' of each plotted genome, plus the 'plotting_name' that you desire to appear
  # on the final plot.
genome_metadata_tsv: /path/to/genome_metadata.tsv
# Optional: Tab-separated file containing the accession of each query gene and its corresponding gene name.
  # Should have two columns: 'qseqid' with the accession and 'gene_name' with the corresponding gene name.
  # Genes will be plotted in the order specified in this TSV file.
  # See ExampleData/Example_configs/gene_naming.tsv
gene_metadata_tsv: /path/to/gene_naming.tsv
# Optional: set the cutoff for displayed bootstrap values. Anything above the cutoff will be shown.
bootstrap_cutoff: 80
# Optional: if you want to re-root your tree, then give the exact name of the tip you want to re-root by. Otherwise, 'NA'.
root_name: NA


## BLAST settings
# Only hits with e-value below this number will be kept
e_value_cutoff: 1e-40
# Only hits with percent amino acid identity above this number will be kept
minimum_percent_identity: 25

